### PR TITLE
Update BuildGuideCrossCompilation.md

### PR DESCRIPTION
**Pull request by adikachal**
we are already inside tensorflow directory see line 144
So should remove one "tensorflow" from the cp command

### CODE REVIEW

**Comment by FrancisMurtagh-arm** [comment]
Hi @adikachal 

The cp command uses .. to go out of the tensorflow directory and then in again into the tensorflow/tensorflow/lite subdirectory which you can see is correct going by tensorflow git repo directory structure, although it is a bit confusing:

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/schema

**Comment by adikachal** [comment]
@FrancisMurtagh-arm  
Collaborator
FrancisMurtagh-arm

This is the original syntax:
mkdir tflite
cd tflite
cp ../tensorflow/tensorflow/lite/schema/schema.fbs .

so to the best I understand the ../ actually takes us out of tflite directory, isnt it?

**Comment by FrancisMurtagh-arm** [comment]
Hi @adikachal, 

You're correct I didn't spot the tflite directory thanks.

We have a process for external contributions outlined here:
https://github.com/ARM-software/armnn/tree/master#contributions

However, I will add a patch to Gerrit as it's such a small change.

Thanks,
Francis.

**Comment by FrancisMurtagh-arm** [comment]
Hi @adikachal,

This is the patch to fix guide, it's done so as to match other guides/scripts.

https://review.mlplatform.org/c/ml/armnn/+/6077

Thanks,
Francis.

**Pull request closed without merging**
