### PR TITLE
Improve TfLiteParser to support more models

### PR DESCRIPTION
**Pull request by brunomorishita**
It supports now:

- Mobilenet_V2_1.0_224
- ResNet_V2_101
- Inception_V3_quant
- Inception_V4_quant
- MnasNet_1.3_224

### CODE REVIEW

**Comment by brunomorishita** [comment]
Tested with models in this website:

[](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/models.md)

**Comment by MatthewARM** [comment]
Thanks very much for this, @brunomorishita 

I'm sorry to be a pain, but please could you resubmit your work to Gerrit at https://review.mlplatform.org/#/admin/projects/ml/armnn as that is where we host the master development.

If you need any help using Gerrit please let me know.

Matthew

**Comment by brunomorishita** [comment]
Hi, @MatthewARM 

Sorry for the delay in responding. I was in vacation.

I resubmit my work to Gerrit as you said.

Please let me know if there is something missing or wrong with this pull request.

Bruno

**Comment by MatthewARM** [comment]
Great, I can see the changes on Gerrit, we'll discuss it there. Many thanks!

**Comment by MatthewARM** [comment]
Hi @brunomorishita there's a few suggestions on the reviews on Gerrit - are you receiving notifications? Also it would be nice if you joined the armnn-dev mailing list at https://lists.linaro.org/mailman/listinfo/armnn-dev for general development discussions.

All the best,
Matthew

**Pull request closed without merging**
